services:
  frontend:
    build:
      context: ./converter
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: converter
    ports:
      - "80:3000"
    env_file:
      - ${ENV_FILE}

  backend:
    build:
      context: ./converter-api
    container_name: converter-api
    ports:
      - "8000:8000"
    environment:
      - UVICORN_WORKERS=4
